[versions]
# https://github.com/JetBrains/intellij-platform-gradle-plugin/releases
gradleIntelliJPlatform = "2.11.0"
# https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library
kotlin = "2.2.20"
# https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/rider/riderRD/maven-metadata.xml
# https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/rider/riderRD/maven-metadata.xml
riderSdkPreview = "2025.3.1"
riderSdk = "2025.3.1"
# https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/maven-metadata.xml
# https://d2s4y8xcwt8bet.cloudfront.net/com/jetbrains/intellij/idea/ideaIC/maven-metadata.xml
ideaSdk = "2025.3.1"

[libraries]
intelliJPlatformModulePlugin = { group = "org.jetbrains.intellij.platform.module", name = "org.jetbrains.intellij.platform.module.gradle.plugin", version.ref = "gradleIntelliJPlatform" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
intelliJPlatformPlugin = { group = "org.jetbrains.intellij.platform", name = "org.jetbrains.intellij.platform.gradle.plugin", version.ref = "gradleIntelliJPlatform" }

[plugins]
# https://github.com/JetBrains/gradle-changelog-plugin/releases/tag/v2.2.1
changelog = "org.jetbrains.changelog:2.5.0"
# https://github.com/mfilippov/gradle-jvm-wrapper
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.15.0"
